### PR TITLE
Upgrade to build using Slicer 5.10 

### PR DESCRIPTION
**Pull request by sadhana-r**

### CODE REVIEW

**Comment by ebrahimebrahim** [comment]
When building this on linux  I get the error

```
error: 'Slicer_EXTENSIONS_DIRBASENAME' was not declared in this scope
```
at Base/Logic/Testing/vtkSlicerApplicationLogicTest1.cxx:244

during the superbuild build step.

Looking into it.

(Since the failure is in a test, we could disable [BUILD_TESTING](https://github.com/OpenwaterHealth/OpenLIFU-app/blob/9397aa35d2f121ea8037c83b195c040442167190/CMakeLists.txt#L88) as a quick fix maybe, but we shouldn't be forced to do that.)

**Comment by ebrahimebrahim** [comment]
Now just awaiting this to be done: https://github.com/OpenwaterHealth/OpenLIFU-python/pull/410

**Comment by ebrahimebrahim** [comment]
kwave upgrade [done](https://github.com/OpenwaterHealth/OpenLIFU-python/pull/410) in OpenLIFU-python.

Now just waiting for the next SlicerOpenLIFU release that includes that update. Then we can bump the SlicerOpenLIFU version and here and this should be good to merge.
